<?php

namespace Database\Seeders;

use App\Models\Flight;

use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FlightTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Flight::insert([
            ['flight_number' => 'SO123', 'departure_date' => now()->toDateString(), 'arrival_date' => now()->addDays(1)->toDateString(), 'departure_time' => '08:00:00', 'arrival_time' => '10:00:00', 'aircraft_type' => 'Boeing 737', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 1 - Check-in A', 'ticket_price' => 150.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi', 'In-flight Entertainment']), 'origin' => 'Schiphol Orbital', 'destination' => 'London Heathrow', 'seats_total' => 180, 'seats_booked' => 50, 'flight_coordinator_id' => 1, 'gate_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO456', 'departure_date' => now()->addDays(1)->toDateString(), 'arrival_date' => now()->addDays(2)->toDateString(), 'departure_time' => '12:00:00', 'arrival_time' => '14:30:00', 'aircraft_type' => 'Airbus A320', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 1 - Check-in B', 'ticket_price' => 200.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi', 'Extra Legroom']), 'origin' => 'Paris Charles de Gaulle', 'destination' => 'Schiphol Orbital', 'seats_total' => 150, 'seats_booked' => 75, 'flight_coordinator_id' => 2, 'gate_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO789', 'departure_date' => now()->addDays(2)->toDateString(), 'arrival_date' => now()->addDays(3)->toDateString(), 'departure_time' => '15:00:00', 'arrival_time' => '17:45:00', 'aircraft_type' => 'Boeing 777', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 2 - Check-in C', 'ticket_price' => 300.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi', 'Premium Meals']), 'origin' => 'Schiphol Orbital', 'destination' => 'New York JFK', 'seats_total' => 250, 'seats_booked' => 100, 'flight_coordinator_id' => 3, 'gate_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO101', 'departure_date' => now()->addDays(3)->toDateString(), 'arrival_date' => now()->addDays(4)->toDateString(), 'departure_time' => '09:30:00', 'arrival_time' => '11:15:00', 'aircraft_type' => 'Embraer E190', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 1 - Check-in D', 'ticket_price' => 120.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi']), 'origin' => 'Berlin Brandenburg', 'destination' => 'Schiphol Orbital', 'seats_total' => 100, 'seats_booked' => 40, 'flight_coordinator_id' => 4, 'gate_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO202', 'departure_date' => now()->addDays(4)->toDateString(), 'arrival_date' => now()->addDays(5)->toDateString(), 'departure_time' => '18:00:00', 'arrival_time' => '20:30:00', 'aircraft_type' => 'Airbus A380', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 3 - Check-in E', 'ticket_price' => 500.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi', 'Lounge Access', 'Premium Meals']), 'origin' => 'Dubai International', 'destination' => 'Schiphol Orbital', 'seats_total' => 500, 'seats_booked' => 300, 'flight_coordinator_id' => 5, 'gate_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO303', 'departure_date' => now()->addDays(5)->toDateString(), 'arrival_date' => now()->addDays(6)->toDateString(), 'departure_time' => '07:00:00', 'arrival_time' => '09:30:00', 'aircraft_type' => 'Boeing 747', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 2 - Check-in F', 'ticket_price' => 400.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi', 'Premium Meals']), 'origin' => 'Los Angeles LAX', 'destination' => 'Schiphol Orbital', 'seats_total' => 300, 'seats_booked' => 200, 'flight_coordinator_id' => 6, 'gate_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO404', 'departure_date' => now()->addDays(6)->toDateString(), 'arrival_date' => now()->addDays(7)->toDateString(), 'departure_time' => '13:00:00', 'arrival_time' => '15:45:00', 'aircraft_type' => 'Airbus A350', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 3 - Check-in G', 'ticket_price' => 450.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi', 'Lounge Access']), 'origin' => 'Tokyo Narita', 'destination' => 'Schiphol Orbital', 'seats_total' => 350, 'seats_booked' => 250, 'flight_coordinator_id' => 7, 'gate_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO505', 'departure_date' => now()->addDays(7)->toDateString(), 'arrival_date' => now()->addDays(8)->toDateString(), 'departure_time' => '10:00:00', 'arrival_time' => '12:30:00', 'aircraft_type' => 'Boeing 787', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 1 - Check-in H', 'ticket_price' => 350.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi', 'In-flight Entertainment']), 'origin' => 'Singapore Changi', 'destination' => 'Schiphol Orbital', 'seats_total' => 280, 'seats_booked' => 180, 'flight_coordinator_id' => 1, 'gate_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO606', 'departure_date' => now()->addDays(8)->toDateString(), 'arrival_date' => now()->addDays(9)->toDateString(), 'departure_time' => '16:00:00', 'arrival_time' => '18:45:00', 'aircraft_type' => 'Boeing 737', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 2 - Check-in I', 'ticket_price' => 200.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi']), 'origin' => 'Madrid Barajas', 'destination' => 'Schiphol Orbital', 'seats_total' => 180, 'seats_booked' => 90, 'flight_coordinator_id' => 2, 'gate_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO707', 'departure_date' => now()->addDays(9)->toDateString(), 'arrival_date' => now()->addDays(10)->toDateString(), 'departure_time' => '11:00:00', 'arrival_time' => '13:30:00', 'aircraft_type' => 'Airbus A320', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 3 - Check-in J', 'ticket_price' => 250.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi', 'Extra Legroom']), 'origin' => 'Rome Fiumicino', 'destination' => 'Schiphol Orbital', 'seats_total' => 200, 'seats_booked' => 100, 'flight_coordinator_id' => 3, 'gate_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO808', 'departure_date' => now()->toDateString(), 'arrival_date' => now()->addDays(1)->toDateString(), 'departure_time' => '14:00:00', 'arrival_time' => '16:00:00', 'aircraft_type' => 'Embraer E195', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 1 - Check-in B', 'ticket_price' => 180.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi']), 'origin' => 'Brussels Airport', 'destination' => 'Schiphol Orbital', 'seats_total' => 120, 'seats_booked' => 60, 'flight_coordinator_id' => 4, 'gate_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO909', 'departure_date' => now()->toDateString(), 'arrival_date' => now()->addDays(1)->toDateString(), 'departure_time' => '17:00:00', 'arrival_time' => '19:00:00', 'aircraft_type' => 'Boeing 737 MAX', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 2 - Check-in D', 'ticket_price' => 220.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi', 'In-flight Entertainment']), 'origin' => 'Copenhagen Kastrup', 'destination' => 'Schiphol Orbital', 'seats_total' => 160, 'seats_booked' => 80, 'flight_coordinator_id' => 5, 'gate_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO010', 'departure_date' => now()->addDays(1)->toDateString(), 'arrival_date' => now()->addDays(2)->toDateString(), 'departure_time' => '06:00:00', 'arrival_time' => '08:00:00', 'aircraft_type' => 'Bombardier CRJ900', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 1 - Check-in E', 'ticket_price' => 140.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi']), 'origin' => 'Dublin Airport', 'destination' => 'Schiphol Orbital', 'seats_total' => 100, 'seats_booked' => 40, 'flight_coordinator_id' => 6, 'gate_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO111', 'departure_date' => now()->addDays(1)->toDateString(), 'arrival_date' => now()->addDays(2)->toDateString(), 'departure_time' => '21:00:00', 'arrival_time' => '23:30:00', 'aircraft_type' => 'Airbus A321neo', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 2 - Check-in G', 'ticket_price' => 210.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi', 'Extra Legroom']), 'origin' => 'Vienna International', 'destination' => 'Schiphol Orbital', 'seats_total' => 180, 'seats_booked' => 90, 'flight_coordinator_id' => 7, 'gate_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO212', 'departure_date' => now()->addDays(2)->toDateString(), 'arrival_date' => now()->addDays(3)->toDateString(), 'departure_time' => '05:30:00', 'arrival_time' => '08:00:00', 'aircraft_type' => 'Boeing 757', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 1 - Check-in H', 'ticket_price' => 260.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi', 'In-flight Entertainment']), 'origin' => 'Zurich Airport', 'destination' => 'Schiphol Orbital', 'seats_total' => 220, 'seats_booked' => 130, 'flight_coordinator_id' => 1, 'gate_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO313', 'departure_date' => now()->addDays(2)->toDateString(), 'arrival_date' => now()->addDays(3)->toDateString(), 'departure_time' => '19:00:00', 'arrival_time' => '21:30:00', 'aircraft_type' => 'Boeing 767', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 3 - Check-in J', 'ticket_price' => 280.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi', 'Premium Meals']), 'origin' => 'Lisbon Portela', 'destination' => 'Schiphol Orbital', 'seats_total' => 250, 'seats_booked' => 170, 'flight_coordinator_id' => 2, 'gate_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO414', 'departure_date' => now()->addDays(3)->toDateString(), 'arrival_date' => now()->addDays(4)->toDateString(), 'departure_time' => '08:00:00', 'arrival_time' => '10:15:00', 'aircraft_type' => 'Airbus A310', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 1 - Check-in C', 'ticket_price' => 190.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi', 'Extra Legroom']), 'origin' => 'Prague Vaclav Havel', 'destination' => 'Schiphol Orbital', 'seats_total' => 200, 'seats_booked' => 100, 'flight_coordinator_id' => 3, 'gate_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO515', 'departure_date' => now()->addDays(3)->toDateString(), 'arrival_date' => now()->addDays(4)->toDateString(), 'departure_time' => '22:00:00', 'arrival_time' => '00:30:00', 'aircraft_type' => 'Airbus A220', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 2 - Check-in F', 'ticket_price' => 160.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi']), 'origin' => 'Stockholm Arlanda', 'destination' => 'Schiphol Orbital', 'seats_total' => 150, 'seats_booked' => 70, 'flight_coordinator_id' => 5, 'gate_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO616', 'departure_date' => now()->addDays(4)->toDateString(), 'arrival_date' => now()->addDays(5)->toDateString(), 'departure_time' => '07:45:00', 'arrival_time' => '10:15:00', 'aircraft_type' => 'Boeing 777X', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 3 - Check-in A', 'ticket_price' => 320.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi', 'Premium Meals', 'Lounge Access']), 'origin' => 'Helsinki Vantaa', 'destination' => 'Schiphol Orbital', 'seats_total' => 300, 'seats_booked' => 220, 'flight_coordinator_id' => 6, 'gate_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO717', 'departure_date' => now()->addDays(4)->toDateString(), 'arrival_date' => now()->addDays(5)->toDateString(), 'departure_time' => '18:30:00', 'arrival_time' => '21:00:00', 'aircraft_type' => 'Airbus A350-1000', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 1 - Check-in G', 'ticket_price' => 380.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi', 'Extra Legroom', 'Premium Meals']), 'origin' => 'Munich Airport', 'destination' => 'Schiphol Orbital', 'seats_total' => 350, 'seats_booked' => 270, 'flight_coordinator_id' => 7, 'gate_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['flight_number' => 'SO818', 'departure_date' => now()->addDays(5)->toDateString(), 'arrival_date' => now()->addDays(6)->toDateString(), 'departure_time' => '12:00:00', 'arrival_time' => '14:30:00', 'aircraft_type' => 'Boeing 737-800', 'airline' => 'Orbital Airlines', 'flight_status' => 'Scheduled', 'check_in_location' => 'Terminal 2 - Check-in B', 'ticket_price' => 170.00, 'ticket_status' => 'Available', 'services' => json_encode(['WiFi']), 'origin' => 'Barcelona El Prat', 'destination' => 'Schiphol Orbital', 'seats_total' => 160, 'seats_booked' => 80, 'flight_coordinator_id' => 1, 'gate_id' => 1, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
